_target_: calvin_agent.models.perceptual_encoders.concat_encoders.ConcatEncoders
_recursive_: false

defaults:
 - vision_static: none
 - vision_gripper: none
 - depth_static: default
 - depth_gripper: none
 - seg_static: default
 - seg_gripper: none
 - proprio: identity
 - tactile: none
