defaults:
  - perceptual_encoder: default
  - visual_goal: default
  - language_goal: default
  - action_decoder: logistic
  - optimizer: adam

_target_: calvin_agent.models.simple_il.SimpleIL
_recursive_: false

replan_freq: 30
